// This file is @generated by prost-build.
/// Start detection request
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartDetectionRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartDetectionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub video_feed_url: ::prost::alloc::string::String,
}
/// Stop detection request
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopDetectionRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StopDetectionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Get status request
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetStatusRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(bool, tag = "1")]
    pub is_running: bool,
    #[prost(string, tag = "2")]
    pub current_model: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub confidence_threshold: f32,
    #[prost(message, optional, tag = "5")]
    pub stats: ::core::option::Option<Stats>,
    #[prost(message, optional, tag = "6")]
    pub protocols: ::core::option::Option<Protocols>,
    /// false → Start is refused, the UI says why
    #[prost(bool, tag = "7")]
    pub camera_connected: bool,
}
/// Live performance counters surfaced on /api/v1/status and /api/v1/stats.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Stats {
    #[prost(float, tag = "1")]
    pub fps: f32,
    /// milliseconds
    #[prost(float, tag = "2")]
    pub inference_time: f32,
    /// detections in the most recent frame
    #[prost(uint32, tag = "3")]
    pub detections: u32,
    #[prost(uint64, tag = "4")]
    pub frames_with_detections: u64,
}
/// Stream ports advertised to the frontend.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Protocols {
    #[prost(uint32, tag = "2")]
    pub http_port: u32,
}
/// Stream detections request
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StreamRequest {
    /// Maximum FPS to stream (0 = no limit)
    #[prost(uint32, tag = "1")]
    pub max_fps: u32,
}
/// One processed frame plus the detections found in it.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectionResult {
    /// JPEG encoded frame
    #[prost(bytes = "vec", tag = "1")]
    pub frame_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "2")]
    pub detections_count: u32,
    #[prost(message, repeated, tag = "3")]
    pub detections: ::prost::alloc::vec::Vec<Detection>,
    /// milliseconds
    #[prost(float, tag = "4")]
    pub inference_time: f32,
    /// capture time (epoch ms)
    #[prost(uint64, tag = "5")]
    pub timestamp: u64,
}
/// A single detected object.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Detection {
    #[prost(uint32, tag = "1")]
    pub class_id: u32,
    #[prost(string, tag = "2")]
    pub class_name: ::prost::alloc::string::String,
    /// 0.0–1.0
    #[prost(float, tag = "3")]
    pub confidence: f32,
    #[prost(message, optional, tag = "4")]
    pub bbox: ::core::option::Option<BoundingBox>,
}
/// Axis-aligned bounding box in normalized \[0,1\] frame coordinates.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct BoundingBox {
    /// top-left x
    #[prost(float, tag = "1")]
    pub x: f32,
    /// top-left y
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub width: f32,
    #[prost(float, tag = "4")]
    pub height: f32,
}
/// Select model request
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelectModelRequest {
    #[prost(string, tag = "1")]
    pub model_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SelectModelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub model_path: ::prost::alloc::string::String,
    #[prost(bool, tag = "4")]
    pub was_running: bool,
}
/// List models request
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListModelsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListModelsResponse {
    #[prost(message, repeated, tag = "1")]
    pub models: ::prost::alloc::vec::Vec<ModelInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub size: u64,
    #[prost(double, tag = "3")]
    pub modified: f64,
    #[prost(bool, tag = "4")]
    pub is_active: bool,
}
/// Upload model request
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelChunk {
    #[prost(oneof = "model_chunk::Data", tags = "1, 2")]
    pub data: ::core::option::Option<model_chunk::Data>,
}
/// Nested message and enum types in `ModelChunk`.
pub mod model_chunk {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "1")]
        Metadata(super::ModelMetadata),
        #[prost(bytes, tag = "2")]
        Chunk(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModelMetadata {
    #[prost(string, tag = "1")]
    pub filename: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub total_size: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadModelResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub model_path: ::prost::alloc::string::String,
}
/// Set threshold request
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SetThresholdRequest {
    #[prost(float, tag = "1")]
    pub threshold: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SetThresholdResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(float, tag = "3")]
    pub threshold: f32,
}
/// Get config request
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetConfigRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConfigResponse {
    #[prost(string, tag = "1")]
    pub capture_device: ::prost::alloc::string::String,
    #[prost(int32, repeated, tag = "2")]
    pub capture_resolution: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "3")]
    pub capture_framerate: i32,
    #[prost(string, tag = "4")]
    pub model_path: ::prost::alloc::string::String,
    #[prost(float, tag = "5")]
    pub confidence_threshold: f32,
}
/// Update config request
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateConfigRequest {
    #[prost(string, optional, tag = "1")]
    pub capture_device: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int32, optional, tag = "2")]
    pub capture_framerate: ::core::option::Option<i32>,
    #[prost(float, optional, tag = "3")]
    pub confidence_threshold: ::core::option::Option<f32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateConfigResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// Get classes request
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetClassesRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetClassesResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub classes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Upload classes request
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadClassesRequest {
    /// Classes separated by newlines
    #[prost(string, tag = "1")]
    pub classes_content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UploadClassesResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "3")]
    pub classes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
