//! Conecsa Object Detection — frontend crate (WASM only).
//!
//! Compiles to **`wasm32`**: the Leptos single-page app served by Nginx in the
//! web deployment. Entry point: `main` (the `#[wasm_bindgen(start)]` hook), which
//! mounts `app::App`. UI lives in the `components` module; HTTP/SSE backend access
//! in [`api`].
//!
//! All content is gated to `wasm32` so that host-target builds of the workspace
//! treat this as an empty crate (the app is only ever built for the browser via
//! Trunk).

// ── WASM-only modules ──────────────────────────────────────────────────────────
// Translations module generated by `leptos_i18n_build` in build.rs from the
// repo-root `i18n/system-vision/` catalogs; injects `pub mod i18n`.
#[cfg(target_arch = "wasm32")]
include!(concat!(env!("OUT_DIR"), "/i18n/mod.rs"));

#[cfg(target_arch = "wasm32")]
pub mod api;
#[cfg(target_arch = "wasm32")]
pub mod app;
#[cfg(target_arch = "wasm32")]
pub mod class_color;
#[cfg(target_arch = "wasm32")]
pub mod components;
#[cfg(target_arch = "wasm32")]
pub mod models;
#[cfg(target_arch = "wasm32")]
pub mod proto;

// ── WASM entry point ──────────────────────────────────────────────────────────
// Excluded under `cfg(test)`: the wasm-bindgen-test harness provides its own
// entry point, and two `#[wasm_bindgen(start)]`/`main` symbols collide.
#[cfg(all(target_arch = "wasm32", not(test)))]
use app::*;
#[cfg(all(target_arch = "wasm32", not(test)))]
use leptos::prelude::*;
#[cfg(all(target_arch = "wasm32", not(test)))]
use wasm_bindgen::prelude::*;

#[cfg(all(target_arch = "wasm32", not(test)))]
#[wasm_bindgen(start)]
pub fn main() {
    console_error_panic_hook::set_once();
    mount_to_body(|| {
        view! {
            <crate::i18n::I18nContextProvider>
                <App/>
            </crate::i18n::I18nContextProvider>
        }
    })
}
