BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*.bb \
            ${LAYERDIR}/recipes-*/*.bbappend \
            ${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-conecsa"
BBFILE_PATTERN_meta-conecsa = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-conecsa = "10"

LAYERSERIES_COMPAT_meta-conecsa = "scarthgap"

LAYERDEPENDS_meta-conecsa = "\
    core \
    openembedded-layer \
    meta-python \
    virtualization-layer \
    tegra \
    "

LAYERVERSION_meta-conecsa = "1"
