"""MkDocs ``gen-files`` hook: build the auto-generated reference pages.

Runs on every ``mkdocs build`` / ``mkdocs serve``. It produces, as *virtual*
files (nothing is written to the working tree):

* ``reference/proto.md`` — rendered from the live ``.proto`` files by
  :mod:`scripts.gen-proto-docs`.
* ``reference/python-api/**`` — one page per Python module across the four
  services, each containing a single mkdocstrings ``:::`` directive. griffe
  parses the source statically, so no service dependency needs to be installed.
* ``reference/python-api/SUMMARY.md`` — consumed by the ``literate-nav`` plugin
  to build the section's navigation tree.
"""

from __future__ import annotations

import importlib.util
import logging
import sys
from pathlib import Path

import mkdocs_gen_files

# griffe emits a WARNING for every parameter/return that a docstring documents
# without a type annotation. Many signatures here are intentionally untyped, so
# these are noise. Drop just those records (via a filter on mkdocs' log
# handlers, which also feed its strict-mode warning counter) while leaving
# mkdocs' own link/nav validation strict.
class _DropGriffeTypeWarnings(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:  # noqa: A003
        return "No type or annotation for" not in record.getMessage()


_griffe_filter = _DropGriffeTypeWarnings()
for _logger in (logging.getLogger(), logging.getLogger("mkdocs")):
    _logger.addFilter(_griffe_filter)
    for _handler in _logger.handlers:
        _handler.addFilter(_griffe_filter)

REPO_ROOT = Path(__file__).resolve().parent.parent

# (service label, source root) — the root is what mkdocstrings has on its
# ``paths``; module identifiers are computed relative to it.
SERVICES: list[tuple[str, str]] = [
    ("inference-service", "inference-service"),
    ("api-gateway", "api-gateway"),
    ("os-base", "os-base"),
    ("training-service", "training-service"),
]

# Directories never worth documenting (generated stubs, venvs, caches, tests).
SKIP_DIRS = {"proto", "__pycache__", ".venv", "venv", "tests", "node_modules"}


def _load_proto_renderer():
    """Import ``scripts/gen-proto-docs.py`` (hyphenated → load by path)."""
    spec = importlib.util.spec_from_file_location(
        "gen_proto_docs", REPO_ROOT / "scripts" / "gen-proto-docs.py"
    )
    if spec is None or spec.loader is None:
        raise ImportError("could not load scripts/gen-proto-docs.py")
    module = importlib.util.module_from_spec(spec)
    # Register before exec so dataclasses can resolve the module's namespace.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def _emit_proto_page() -> None:
    renderer = _load_proto_renderer()
    with mkdocs_gen_files.open("reference/proto.md", "w") as fd:
        fd.write(renderer.render_all())


# Landing page for the Rust API docs. It is a placeholder so the ``nav`` entry
# resolves during ``mkdocs build``; ``scripts/build-docs.sh`` overlays the real
# ``cargo doc`` output (the per-crate folders) into ``site/rust/`` afterwards.
_RUST_LANDING = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><title>Rust API</title></head>
<body style="font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto;">
<h1>Rust API reference</h1>
<p>Generated by <code>cargo doc</code>. If you see this placeholder, run
<code>scripts/build-docs.sh</code> (or the docs CI) to build the crate docs.</p>
<ul>
  <li><a href="conecsa_system_vision/index.html">conecsa-system-vision (system-vision — Leptos/WASM + Tauri)</a></li>
  <li><a href="webcam_server/index.html">webcam-server (Tokio V4L2 camera server)</a></li>
</ul>
</body></html>
"""


def _emit_rust_landing() -> None:
    with mkdocs_gen_files.open("rust/index.html", "w") as fd:
        fd.write(_RUST_LANDING)


def _module_identifier(root: Path, py_file: Path) -> str | None:
    """Dotted import path for *py_file* relative to its source *root*."""
    rel_parts = py_file.relative_to(root).parts
    # Top-level standalone modules (e.g. each service's thin ``main.py``) share
    # the same identifier across roots and would collide in griffe — skip them.
    if len(rel_parts) == 1 and py_file.name != "__init__.py":
        return None
    rel = py_file.relative_to(root).with_suffix("")
    parts = list(rel.parts)
    if any(part in SKIP_DIRS for part in parts):
        return None
    if py_file.name.endswith("_pb2.py") or py_file.name.endswith("_pb2_grpc.py"):
        return None
    if parts[-1] == "__init__":
        parts = parts[:-1]
    if not parts:
        return None
    return ".".join(parts)


_PY_API_INDEX = """# Python API reference

Auto-generated from the source by [mkdocstrings](https://mkdocstrings.github.io/)
(static parsing via griffe — no imports, no CUDA/torch needed). One page per
module, grouped by service:

- **inference-service** — the `api` package (TensorRT pipeline, detection,
  model management, runtimes).
- **api-gateway** — the `gateway` package (Flask routes, gRPC clients, SHM
  media, SSE).
- **os-base** — the `agent` (hardware gRPC service) and `conecsa_shm` (ring helpers) packages.
- **training-service** — the `service` package (datasets, labeling, training).

Use the navigation on the left to browse the modules.
"""


def _emit_python_pages() -> None:
    # Nav is re-exported without being in mkdocs_gen_files' __all__; it is the
    # documented entry point for building the literate-nav SUMMARY.
    nav = mkdocs_gen_files.Nav()  # pyright: ignore[reportPrivateImportUsage]
    with mkdocs_gen_files.open("reference/python-api/index.md", "w") as fd:
        fd.write(_PY_API_INDEX)
    for label, root_name in SERVICES:
        root = REPO_ROOT / root_name
        for py_file in sorted(root.rglob("*.py")):
            identifier = _module_identifier(root, py_file)
            if identifier is None:
                continue
            doc_path = Path("reference", "python-api", label, *identifier.split(".")).with_suffix(".md")
            nav[(label, *identifier.split("."))] = doc_path.relative_to("reference/python-api").as_posix()
            with mkdocs_gen_files.open(doc_path, "w") as fd:
                fd.write(f"# `{identifier}`\n\n::: {identifier}\n")
            mkdocs_gen_files.set_edit_path(
                doc_path, py_file.relative_to(REPO_ROOT)
            )
    with mkdocs_gen_files.open("reference/python-api/SUMMARY.md", "w") as fd:
        fd.write("* [Overview](index.md)\n")
        fd.writelines(nav.build_literate_nav())


_emit_proto_page()
_emit_rust_landing()
_emit_python_pages()
